FROM python:3.6-alpine
COPY server.py /server.py
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN apk update py-pip
RUN pip install psycopg2

CMD sh -c "python3 /server.py; sleep 1;"
